/**
 * Bible story catalog — the core content dataset for the app.
 *
 * Each story has metadata used for:
 * - Display: title, category, themes, testament
 * - AI generation: scriptureRef tells Claude which passage to retell
 * - Bookshelf: category groups stories into shelves
 * - Progress: id tracks which stories have been heard
 */

export const STORY_CATEGORIES = [
  'Holiday Stories',
  'Old Testament Adventures',
  'New Testament Stories',
  'Parables & Teachings',
  'Heroes of Faith',
  'Miracles & Wonders',
] as const;

export type StoryCategory = (typeof STORY_CATEGORIES)[number];

export const STORY_THEMES = [
  'Courage',
  'Kindness',
  'Faith',
  'Forgiveness',
  'Obedience',
  'Love',
  'Hope',
  'Patience',
  'Wisdom',
  'Trust',
  'Gratitude',
  'Perseverance',
] as const;

export type StoryTheme = (typeof STORY_THEMES)[number];

export interface BibleStory {
  id: string;
  title: string;
  testament: 'Old Testament' | 'New Testament';
  category: StoryCategory;
  themes: StoryTheme[];
  scriptureRef: string;
  /** Brief teaser for the Tonight's Story card (1 sentence) */
  teaser: string;
}

/**
 * 71 Bible stories suitable for bedtime reading to children ages 6-12.
 * Ordered roughly chronologically within each testament.
 * Holiday Stories follow the liturgical calendar (Advent → Pentecost).
 */
export const BIBLE_STORIES: BibleStory[] = [
  // ── Old Testament Adventures ──────────────────────────────────────
  {
    id: 'creation',
    title: 'The Creation of the World',
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Gratitude', 'Love'],
    scriptureRef: 'Genesis 1:1–2:3',
    teaser: 'In the beginning, God spoke light into the darkness.',
  },
  {
    id: 'adam-and-eve',
    title: 'Adam and Eve in the Garden',
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Obedience', 'Trust'],
    scriptureRef: 'Genesis 2:4–3:24',
    teaser: 'A beautiful garden, a single rule, and the choice that changed everything.',
  },
  {
    id: 'noahs-ark',
    title: "Noah's Ark",
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Faith', 'Obedience', 'Trust'],
    scriptureRef: 'Genesis 6:9–9:17',
    teaser: 'Rain begins to fall, and one faithful man builds a boat like no other.',
  },
  {
    id: 'tower-of-babel',
    title: 'The Tower of Babel',
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Wisdom', 'Obedience'],
    scriptureRef: 'Genesis 11:1-9',
    teaser: 'A city builds a tower to reach the sky — but the sky has other plans.',
  },
  {
    id: 'abrahams-journey',
    title: "Abraham's Journey",
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Faith', 'Trust', 'Courage'],
    scriptureRef: 'Genesis 12:1-9',
    teaser: 'Leave everything behind and follow a promise you cannot see.',
  },
  {
    id: 'abraham-and-isaac',
    title: 'Abraham and Isaac',
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Faith', 'Trust', 'Obedience'],
    scriptureRef: 'Genesis 22:1-19',
    teaser: 'The hardest test of faith a father could ever face.',
  },
  {
    id: 'jacob-and-esau',
    title: 'Jacob and Esau',
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Forgiveness', 'Patience'],
    scriptureRef: 'Genesis 25:19-34; 27:1-45; 33:1-11',
    teaser: 'Twin brothers, a stolen blessing, and the long road to forgiveness.',
  },
  {
    id: 'josephs-coat',
    title: "Joseph's Colorful Coat",
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Perseverance', 'Forgiveness', 'Hope'],
    scriptureRef: 'Genesis 37:1-36',
    teaser: 'A coat of many colors and brothers filled with jealousy.',
  },
  {
    id: 'joseph-in-egypt',
    title: 'Joseph in Egypt',
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Perseverance', 'Wisdom', 'Forgiveness'],
    scriptureRef: 'Genesis 39–45',
    teaser: 'From prison to palace — a dreamer who never stopped trusting.',
  },
  {
    id: 'baby-moses',
    title: 'Baby Moses in the Basket',
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Courage', 'Hope', 'Trust'],
    scriptureRef: 'Exodus 2:1-10',
    teaser: 'A tiny basket floats down the river, carrying the future of a nation.',
  },
  {
    id: 'burning-bush',
    title: 'Moses and the Burning Bush',
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Courage', 'Faith', 'Obedience'],
    scriptureRef: 'Exodus 3:1–4:17',
    teaser: 'A bush burns but is never consumed, and a voice speaks your name.',
  },
  {
    id: 'ten-plagues',
    title: 'The Ten Plagues of Egypt',
    testament: 'Old Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Courage'],
    scriptureRef: 'Exodus 7–12',
    teaser: 'Darkness falls, rivers turn red, and Pharaoh faces the power of God.',
  },
  {
    id: 'parting-red-sea',
    title: 'Crossing the Red Sea',
    testament: 'Old Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Trust', 'Courage'],
    scriptureRef: 'Exodus 14:1-31',
    teaser: 'Trapped between an army and the sea — until the waters part.',
  },
  {
    id: 'ten-commandments',
    title: 'The Ten Commandments',
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Obedience', 'Wisdom'],
    scriptureRef: 'Exodus 19:1–20:21',
    teaser: 'Thunder shakes the mountain as God writes His rules in stone.',
  },
  {
    id: 'joshua-and-jericho',
    title: 'The Walls of Jericho',
    testament: 'Old Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Obedience', 'Courage'],
    scriptureRef: 'Joshua 6:1-27',
    teaser: 'March, shout, and watch impossible walls come tumbling down.',
  },
  {
    id: 'gideon',
    title: "Gideon's 300 Soldiers",
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Courage', 'Faith', 'Trust'],
    scriptureRef: 'Judges 7:1-25',
    teaser: 'An army of thousands becomes just 300 — and that is enough.',
  },
  {
    id: 'ruth-and-naomi',
    title: 'Ruth and Naomi',
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Love', 'Kindness', 'Perseverance'],
    scriptureRef: 'Ruth 1–4',
    teaser: 'Where you go, I will go. A promise of loyalty that changes two lives.',
  },
  {
    id: 'samuel-called',
    title: 'God Calls Samuel',
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Obedience', 'Faith'],
    scriptureRef: '1 Samuel 3:1-21',
    teaser: 'In the quiet of the night, a young boy hears someone calling his name.',
  },
  {
    id: 'david-and-goliath',
    title: 'David and Goliath',
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Courage', 'Faith', 'Trust'],
    scriptureRef: '1 Samuel 17:1-54',
    teaser: 'A shepherd boy, five smooth stones, and a giant who laughed too soon.',
  },
  {
    id: 'david-and-jonathan',
    title: 'David and Jonathan',
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Love', 'Kindness', 'Courage'],
    scriptureRef: '1 Samuel 18:1-4; 20:1-42',
    teaser: 'The deepest friendship, tested by a jealous king.',
  },
  {
    id: 'solomons-wisdom',
    title: "Solomon's Wisdom",
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Wisdom', 'Kindness'],
    scriptureRef: '1 Kings 3:5-28',
    teaser: 'God offers anything in the world — and a young king asks for wisdom.',
  },
  {
    id: 'elijah-prophets-baal',
    title: 'Elijah and the Prophets of Baal',
    testament: 'Old Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Courage'],
    scriptureRef: '1 Kings 18:1-46',
    teaser: 'One prophet against 450, and fire falls from the sky.',
  },
  {
    id: 'elijah-chariot-fire',
    title: "Elijah's Chariot of Fire",
    testament: 'Old Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Hope'],
    scriptureRef: '2 Kings 2:1-14',
    teaser: 'A whirlwind, a chariot of flame, and a friend who must say goodbye.',
  },
  {
    id: 'naaman-healed',
    title: 'Naaman Is Healed',
    testament: 'Old Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Obedience', 'Kindness'],
    scriptureRef: '2 Kings 5:1-19',
    teaser: 'A proud general and a simple instruction: wash seven times.',
  },
  {
    id: 'esther',
    title: 'Brave Queen Esther',
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Courage', 'Faith', 'Love'],
    scriptureRef: 'Esther 2–8',
    teaser: 'Perhaps you were made queen for such a time as this.',
  },
  {
    id: 'shadrach-meshach-abednego',
    title: 'The Fiery Furnace',
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Courage', 'Faith', 'Trust'],
    scriptureRef: 'Daniel 3:1-30',
    teaser: 'Three friends refuse to bow — and walk through flames unburned.',
  },
  {
    id: 'daniel-lions-den',
    title: "Daniel in the Lions' Den",
    testament: 'Old Testament',
    category: 'Heroes of Faith',
    themes: ['Courage', 'Faith', 'Trust'],
    scriptureRef: 'Daniel 6:1-28',
    teaser: 'Thrown to the lions for praying — but the lions keep their mouths shut.',
  },
  {
    id: 'jonah-whale',
    title: 'Jonah and the Great Fish',
    testament: 'Old Testament',
    category: 'Old Testament Adventures',
    themes: ['Obedience', 'Forgiveness', 'Patience'],
    scriptureRef: 'Jonah 1–4',
    teaser: 'Run from God and end up in the belly of something enormous.',
  },

  // ── Holiday Stories (Liturgical Calendar) ────────────────────────
  {
    id: 'angel-visits-mary',
    title: 'The Angel Visits Mary',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Faith', 'Obedience', 'Hope'],
    scriptureRef: 'Luke 1:26–38',
    teaser: 'An angel appears with an impossible message — and a young woman says yes.',
  },

  // ── New Testament Stories ─────────────────────────────────────────
  {
    id: 'birth-of-jesus',
    title: 'The Birth of Jesus',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Love', 'Hope', 'Gratitude'],
    scriptureRef: 'Luke 2:1-20',
    teaser: 'A stable, a manger, and a sky full of singing angels.',
  },
  {
    id: 'shepherds-and-angels',
    title: 'The Shepherds and the Angels',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Hope', 'Love', 'Gratitude'],
    scriptureRef: 'Luke 2:8–20',
    teaser: 'On a quiet hillside, the sky explodes with angels singing glory to God.',
  },
  {
    id: 'wise-men',
    title: 'The Wise Men Follow the Star',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Faith', 'Wisdom', 'Perseverance'],
    scriptureRef: 'Matthew 2:1-12',
    teaser: 'Travelers from the East follow a star to find a king in the humblest place.',
  },
  {
    id: 'simeon-and-anna',
    title: 'Simeon and Anna at the Temple',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Faith', 'Hope', 'Patience'],
    scriptureRef: 'Luke 2:22–40',
    teaser: 'Two faithful elders have waited their whole lives — and today the promise arrives.',
  },
  {
    id: 'boy-jesus-temple',
    title: 'Young Jesus at the Temple',
    testament: 'New Testament',
    category: 'New Testament Stories',
    themes: ['Wisdom', 'Obedience'],
    scriptureRef: 'Luke 2:41-52',
    teaser: 'A twelve-year-old astonishes the wisest teachers in all of Jerusalem.',
  },
  {
    id: 'jesus-baptism',
    title: 'The Baptism of Jesus',
    testament: 'New Testament',
    category: 'New Testament Stories',
    themes: ['Obedience', 'Love'],
    scriptureRef: 'Matthew 3:13-17',
    teaser: 'The heavens open, a dove descends, and a voice says: This is my Son.',
  },
  {
    id: 'jesus-temptation',
    title: 'Jesus in the Wilderness',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Courage', 'Faith', 'Perseverance'],
    scriptureRef: 'Matthew 4:1-11',
    teaser: 'Forty days alone in the desert, tested three times by the tempter.',
  },
  {
    id: 'disciples-called',
    title: 'Jesus Calls His Disciples',
    testament: 'New Testament',
    category: 'New Testament Stories',
    themes: ['Faith', 'Trust', 'Courage'],
    scriptureRef: 'Mark 1:16-20; Luke 5:1-11',
    teaser: 'Leave your nets, leave your boats — come and follow me.',
  },
  {
    id: 'sermon-on-mount',
    title: 'The Sermon on the Mount',
    testament: 'New Testament',
    category: 'Parables & Teachings',
    themes: ['Kindness', 'Love', 'Wisdom'],
    scriptureRef: 'Matthew 5–7',
    teaser: 'Blessed are the peacemakers, the gentle, the merciful — the kingdom belongs to them.',
  },
  {
    id: 'water-into-wine',
    title: 'Water into Wine',
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Kindness'],
    scriptureRef: 'John 2:1-12',
    teaser: 'A wedding runs out of wine, and water jars become the most amazing drinks.',
  },
  {
    id: 'calming-storm',
    title: 'Jesus Calms the Storm',
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Trust', 'Courage'],
    scriptureRef: 'Mark 4:35-41',
    teaser: 'Waves crash over the boat — but he sleeps on a cushion in the stern.',
  },
  {
    id: 'feeding-5000',
    title: 'Feeding the Five Thousand',
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Kindness', 'Faith', 'Gratitude'],
    scriptureRef: 'John 6:1-15',
    teaser: 'Five loaves. Two fish. Five thousand hungry people. Watch what happens.',
  },
  {
    id: 'walking-on-water',
    title: 'Walking on Water',
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Trust', 'Courage'],
    scriptureRef: 'Matthew 14:22-33',
    teaser: 'A figure walks across the dark waves, and Peter steps out of the boat.',
  },
  {
    id: 'good-samaritan',
    title: 'The Good Samaritan',
    testament: 'New Testament',
    category: 'Parables & Teachings',
    themes: ['Kindness', 'Love', 'Courage'],
    scriptureRef: 'Luke 10:25-37',
    teaser: 'Everyone passes by the wounded man — except the one nobody expected.',
  },
  {
    id: 'prodigal-son',
    title: 'The Prodigal Son',
    testament: 'New Testament',
    category: 'Parables & Teachings',
    themes: ['Forgiveness', 'Love', 'Hope'],
    scriptureRef: 'Luke 15:11-32',
    teaser: 'A son wastes everything and walks home expecting nothing — but his father runs to meet him.',
  },
  {
    id: 'lost-sheep',
    title: 'The Lost Sheep',
    testament: 'New Testament',
    category: 'Parables & Teachings',
    themes: ['Love', 'Kindness'],
    scriptureRef: 'Luke 15:1-7',
    teaser: 'Ninety-nine are safe, but the shepherd goes searching for the one.',
  },
  {
    id: 'mustard-seed',
    title: 'The Mustard Seed',
    testament: 'New Testament',
    category: 'Parables & Teachings',
    themes: ['Faith', 'Hope', 'Patience'],
    scriptureRef: 'Matthew 13:31-32',
    teaser: 'The tiniest seed grows into the biggest tree in the garden.',
  },
  {
    id: 'sower-seeds',
    title: 'The Sower and the Seeds',
    testament: 'New Testament',
    category: 'Parables & Teachings',
    themes: ['Wisdom', 'Patience', 'Faith'],
    scriptureRef: 'Matthew 13:1-23',
    teaser: 'Seeds fall on rocks, thorns, and paths — but some find good soil.',
  },
  {
    id: 'wise-foolish-builders',
    title: 'The Wise and Foolish Builders',
    testament: 'New Testament',
    category: 'Parables & Teachings',
    themes: ['Wisdom', 'Obedience'],
    scriptureRef: 'Matthew 7:24-27',
    teaser: 'Two houses, one storm — only one is still standing when the rain stops.',
  },
  {
    id: 'ten-lepers',
    title: 'The Ten Lepers',
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Gratitude', 'Faith', 'Kindness'],
    scriptureRef: 'Luke 17:11-19',
    teaser: 'Ten are healed. Only one comes back to say thank you.',
  },
  {
    id: 'jairus-daughter',
    title: "Jairus' Daughter",
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Hope', 'Love'],
    scriptureRef: 'Mark 5:21-43',
    teaser: 'They say she is gone, but Jesus takes her hand and whispers: Little girl, get up.',
  },
  {
    id: 'blind-bartimaeus',
    title: 'Blind Bartimaeus',
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Perseverance', 'Hope'],
    scriptureRef: 'Mark 10:46-52',
    teaser: 'Everyone tells him to be quiet, but he shouts even louder.',
  },
  {
    id: 'jesus-and-children',
    title: 'Jesus Blesses the Children',
    testament: 'New Testament',
    category: 'New Testament Stories',
    themes: ['Love', 'Kindness'],
    scriptureRef: 'Mark 10:13-16',
    teaser: 'The disciples try to send the children away — but Jesus calls them closer.',
  },
  {
    id: 'zacchaeus',
    title: 'Zacchaeus the Tax Collector',
    testament: 'New Testament',
    category: 'New Testament Stories',
    themes: ['Forgiveness', 'Kindness', 'Hope'],
    scriptureRef: 'Luke 19:1-10',
    teaser: 'A very short man climbs a very tall tree just to catch a glimpse.',
  },
  {
    id: 'lazarus',
    title: 'Lazarus Raised from the Dead',
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Hope', 'Love'],
    scriptureRef: 'John 11:1-44',
    teaser: 'Four days in the tomb. Then a voice calls out: Lazarus, come forth.',
  },
  {
    id: 'triumphal-entry',
    title: 'The Triumphal Entry',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Love', 'Hope'],
    scriptureRef: 'Matthew 21:1-11',
    teaser: 'Palm branches wave and crowds shout Hosanna as a humble donkey carries a king.',
  },
  {
    id: 'last-supper',
    title: 'The Last Supper',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Love', 'Kindness', 'Gratitude'],
    scriptureRef: 'Matthew 26:17-30',
    teaser: 'A final meal, broken bread, and a promise to remember.',
  },
  {
    id: 'foot-washing',
    title: 'Jesus Washes the Disciples\' Feet',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Love', 'Kindness', 'Obedience'],
    scriptureRef: 'John 13:1–17',
    teaser: 'The king of everything kneels down and washes the dusty feet of his friends.',
  },
  {
    id: 'garden-gethsemane',
    title: 'The Garden of Gethsemane',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Courage', 'Faith', 'Love'],
    scriptureRef: 'Matthew 26:36-46',
    teaser: 'Alone in the garden, praying through the hardest night.',
  },
  {
    id: 'crucifixion',
    title: 'The Crucifixion of Jesus',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Love', 'Courage', 'Hope'],
    scriptureRef: 'Luke 23:26–49',
    teaser: 'The darkest day — when love carried the heaviest weight of all.',
  },
  {
    id: 'resurrection',
    title: 'The Resurrection',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Hope', 'Love', 'Faith'],
    scriptureRef: 'Matthew 28:1-10; John 20:1-18',
    teaser: 'The stone is rolled away. The tomb is empty. He is risen.',
  },
  {
    id: 'road-to-emmaus',
    title: 'The Road to Emmaus',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Hope', 'Faith', 'Wisdom'],
    scriptureRef: 'Luke 24:13-35',
    teaser: 'Two travelers walk with a stranger — and their hearts begin to burn.',
  },
  {
    id: 'doubting-thomas',
    title: 'Doubting Thomas',
    testament: 'New Testament',
    category: 'New Testament Stories',
    themes: ['Faith', 'Trust'],
    scriptureRef: 'John 20:24-29',
    teaser: 'Unless I see it with my own eyes, I will not believe.',
  },
  {
    id: 'ascension',
    title: 'The Ascension of Jesus',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Hope', 'Faith'],
    scriptureRef: 'Acts 1:6-11',
    teaser: 'He rises into the clouds, and two messengers say: He will come back.',
  },
  {
    id: 'pentecost',
    title: 'The Day of Pentecost',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Courage', 'Faith', 'Hope'],
    scriptureRef: 'Acts 2:1-41',
    teaser: 'Wind fills the room, flames appear, and suddenly everyone speaks in tongues.',
  },
  {
    id: 'transfiguration',
    title: 'The Transfiguration',
    testament: 'New Testament',
    category: 'Holiday Stories',
    themes: ['Faith', 'Hope', 'Wisdom'],
    scriptureRef: 'Matthew 17:1–9',
    teaser: 'On a mountaintop, Jesus shines brighter than the sun — and Moses and Elijah appear.',
  },
  {
    id: 'peter-heals-lame-man',
    title: 'Peter Heals the Lame Man',
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Kindness', 'Courage'],
    scriptureRef: 'Acts 3:1-10',
    teaser: 'Silver and gold I do not have, but what I have I give you.',
  },
  {
    id: 'saul-conversion',
    title: "Saul's Conversion on the Road",
    testament: 'New Testament',
    category: 'Heroes of Faith',
    themes: ['Faith', 'Forgiveness', 'Courage'],
    scriptureRef: 'Acts 9:1-22',
    teaser: 'A blinding light on the road, and the greatest enemy becomes the greatest champion.',
  },
  {
    id: 'peter-prison-escape',
    title: "Peter's Miraculous Escape",
    testament: 'New Testament',
    category: 'Miracles & Wonders',
    themes: ['Faith', 'Hope', 'Courage'],
    scriptureRef: 'Acts 12:1-19',
    teaser: 'Chains fall off, doors open on their own, and the guards see nothing.',
  },
  {
    id: 'paul-shipwreck',
    title: "Paul's Shipwreck",
    testament: 'New Testament',
    category: 'Heroes of Faith',
    themes: ['Courage', 'Faith', 'Perseverance'],
    scriptureRef: 'Acts 27:1–28:10',
    teaser: 'A violent storm, a sinking ship, and a voice that says: Do not be afraid.',
  },
  {
    id: 'armor-of-god',
    title: 'The Armor of God',
    testament: 'New Testament',
    category: 'Parables & Teachings',
    themes: ['Courage', 'Faith', 'Wisdom'],
    scriptureRef: 'Ephesians 6:10-18',
    teaser: 'Belt, breastplate, shield, helmet, sword — suit up for the greatest battle.',
  },
  {
    id: 'love-is-patient',
    title: 'Love Is Patient, Love Is Kind',
    testament: 'New Testament',
    category: 'Parables & Teachings',
    themes: ['Love', 'Kindness', 'Patience'],
    scriptureRef: '1 Corinthians 13:1-13',
    teaser: 'The most beautiful description of love ever written.',
  },
];

/**
 * Get a story by its ID.
 */
export function getStoryById(id: string): BibleStory | undefined {
  return BIBLE_STORIES.find((s) => s.id === id);
}

/**
 * Get all stories in a category, for the Bookshelf view.
 */
export function getStoriesByCategory(category: StoryCategory): BibleStory[] {
  return BIBLE_STORIES.filter((s) => s.category === category);
}

/**
 * Get a random story (the "Another Story" button).
 * Optionally exclude a story ID to avoid repeats.
 */
export function getRandomStory(excludeId?: string): BibleStory {
  const pool = excludeId
    ? BIBLE_STORIES.filter((s) => s.id !== excludeId)
    : BIBLE_STORIES;
  return pool[Math.floor(Math.random() * pool.length)];
}

/**
 * Total number of stories in the catalog.
 */
export const TOTAL_STORIES = BIBLE_STORIES.length;
